### ISSUE TITLE
Cannot change URL via curl or url

### ISSUE THREAD

**Issue by rijotech** [greghxc/express-chromix#1]
I can change URL via Swagger UI changing the values but if i try via URL nothing happens 
for example.
via URL
http://192.168.1.222:3000/tabs/2?url=http://localhost/demo.html
or via ssh 
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://192.168.1.222:3000/tabs/2?url=http%3A%2F%2Flocalhost/demo.html%2F'

**Comment by greghxc** [comment]
Hi! I expect this is due to authentication. Basic auth is required for interacting with the API (including via Swagger, where you are prompted by the browser).

**Examples (using a simplified GET):**

**Does not** work (including "i" flag for visibility):

```
curl -iX GET --header 'Accept: application/json' 'http://localhost:3000/tabs'
>> HTTP/1.1 401 Unauthorized
>> X-Powered-By: Express
>> WWW-Authenticate: Basic realm="express-chromix"
>> ...
```

**Does** work (using default credentials):

```
curl -u admin:supersecret -iX GET --header 'Accept: application/json' 'http://localhost:3000/tabs'
>> HTTP/1.1 200 OK
>> X-Powered-By: Express
>> Content-Type: application/json; charset=utf-8
>> [Payload, etc]
```

Or with password prompt:

```
curl -u admin -iX GET --header 'Accept: application/json' 'http://localhost:3000/tabs'
>> HTTP/1.1 200 OK
>> X-Powered-By: Express
>> Content-Type: application/json; charset=utf-8
>> [Payload, etc]
```

Please confirm this is what you are seeing. If this is the case, the code should be updated to reflect this in the Swagger Docs.

**Comment by rijotech** [comment]
This workout for me thanks `curl -u admin:supersecret -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:3000/tabs/2?url=http://yahoo.com'`

**Comment by greghxc** [comment]
Glad it worked, closing issue.
